version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    environment:
      MYSQL_DATABASE: customer_management
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 13306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/customer_management?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false

volumes:
  db:
    driver: local
