server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT:localhost}:3306/customer_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework: WARN
    com.customer_management_api.repository: DEBUG
