server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/customer_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

mybatis:
  configuration:
    map-underscore-to-camel-case: true
