version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  test:
    docker:
      - image: openjdk:17.0.2
      - image: mysql:8
        environment:
          MYSQL_DATABASE: customer_management
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - run: ./mvnw test
  deploy:
    docker:
      - image: openjdk:17.0.2-oraclelinux8
      - image: mysql:8
        environment:
          MYSQL_DATABASE: customer_management
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          DB_USERNAME: admin
          DB_PASSWORD: password
          DB_ENDPOINT: customer-management-database-1.cluster-c37ecyruueoq.ap-northeast-1.rds.amazonaws.com
    steps:
      - checkout
      - run: ./mvnw package spring-boot:repackage
      - run: microdnf install yum
      - run: yum -y install openssh-clients
      - run: ls
      - add_ssh_keys:
          fingerprints:
            - "93:26:32:10:d4:24:6d:f2:1d:75:2a:77:a5:89:ab:b6"
      - run: scp -o "StrictHostKeyChecking=no" target/customer-management-api-0.0.1-SNAPSHOT.jar ec2-user@3.114.212.130:~/
      - run: ssh -o "StrictHostKeyChecking=no" ec2-user@3.114.212.130 'env'
      - run: ssh -o "StrictHostKeyChecking=no" ec2-user@3.114.212.130 'java -jar customer-management-api-0.0.1-SNAPSHOT.jar'

workflows:
  test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
