version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  test:
    docker:
      - image: openjdk:17.0.2
      - image: mysql:8
        environment:
          MYSQL_DATABASE: customer_management
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - run: env
      - run: ./mvnw test
  deploy:
    docker:
      - image: openjdk:17.0.2-oraclelinux8
      - image: mysql:8
        environment:
          MYSQL_DATABASE: customer_management
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
      - checkout
      - run: ./mvnw package spring-boot:repackage
      - run: microdnf install yum
      - run: yum -y install openssh-clients
      - run: ls
      - add_ssh_keys:
          fingerprints:
            - $CIRCLECI_EC2_SSH_KEY
      - run: scp -o "StrictHostKeyChecking=no" target/customer-management-api-0.0.1-SNAPSHOT.jar ec2-user@$CIRCLECI_EC2_ENDPOINT1:~/
      - run: scp -o "StrictHostKeyChecking=no" java.sh ec2-user@$CIRCLECI_EC2_ENDPOINT1:~/
      - run: ssh -o "StrictHostKeyChecking=no" ec2-user@$CIRCLECI_EC2_ENDPOINT1 "export DB_ENDPOINT=$CIRCLECI_DB_ENDPOINT
          && export DB_USERNAME=$CIRCLECI_DB_USERNAME
          && export DB_PASSWORD=$CIRCLECI_DB_PASSWORD
          && bash java.sh customer-management-api-0.0.1-SNAPSHOT.jar"
      - run: scp -o "StrictHostKeyChecking=no" target/customer-management-api-0.0.1-SNAPSHOT.jar ec2-user@$CIRCLECI_EC2_ENDPOINT2:~/
      - run: scp -o "StrictHostKeyChecking=no" java.sh ec2-user@$CIRCLECI_EC2_ENDPOINT2:~/
      - run: ssh -o "StrictHostKeyChecking=no" ec2-user@$CIRCLECI_EC2_ENDPOINT2 "export DB_ENDPOINT=$CIRCLECI_DB_ENDPOINT
          && export DB_USERNAME=$CIRCLECI_DB_USERNAME
          && export DB_PASSWORD=$CIRCLECI_DB_PASSWORD
          && bash java.sh customer-management-api-0.0.1-SNAPSHOT.jar"

workflows:
  test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
