version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  test:
    docker:
      - image: openjdk:17.0.2
      - image: mysql:8
        environment:
          MYSQL_DATABASE: customer_management
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - run: ./mvnw test
  deploy:
    docker:
      - image: openjdk:17.0.2-oraclelinux8
      - image: mysql:8
        environment:
          MYSQL_DATABASE: customer_management
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - run: ls
      - run: ./mvnw package spring-boot:repackage
      - run: ls
      - add_ssh_keys:
          fingerprints:
            - "93:26:32:10:d4:24:6d:f2:1d:75:2a:77:a5:89:ab:b6"
      - run: apt-get update && apt-get -y install openssh-client
        #      - run: scp -o "StrictHostKeyChecking=no" target/customer-management-api-0.0.1-SNAPSHOT.jar ec2-user@3.114.212.130:~/

      #  deploy:
      #    docker:

      #    steps:
      #      - checkout
      #      - add_ssh_keys:
      #          fingerprints:
      #            - "93:26:32:10:d4:24:6d:f2:1d:75:2a:77:a5:89:ab:b6"
      #      - run: scp -o "StrictHostKeyChecking=no" scp target/customer-management-api-0.0.1-SNAPSHOT.jar  ec2-user@3.114.212.130:~/
      #      - run: ssh -o "StrictHostKeyChecking=no" ec2-user@3.114.212.130 'pwd && ls'

workflows:
  test:
    jobs:
      - test
      - deploy
