version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  test:
    docker:
      #      - image: openjdk:17.0.2
      - image: mysql:8
        environment:
          MYSQL_DATABASE: customer_management
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - run: ./mvnw test

workflows:
  test:
    jobs:
      - test
