version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  test:
    docker:
      - image: openjdk:17.0.2
    steps:
      - checkout
      - run: ./mvnw test

workflows:
  test:
    jobs:
      - test
